"""Auto-generated migration for schema sync

Revision ID: 32a4cd4e4edb
Revises: 1388a6f81c7d
Create Date: 2023-12-29 02:59:23.199811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a4cd4e4edb'
down_revision: Union[str, None] = '1388a6f81c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
