"""Auto-generated migration for schema sync

Revision ID: 3fb5334c2fa8
Revises: 3ce6944be709
Create Date: 2023-12-30 19:43:44.981895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb5334c2fa8'
down_revision: Union[str, None] = '3ce6944be709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
