"""Auto-generated migration for schema sync

Revision ID: 8149d7eb969b
Revises: 82b5e0f1c3df
Create Date: 2023-12-31 01:33:08.997412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8149d7eb969b'
down_revision: Union[str, None] = '82b5e0f1c3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('name', sa.String(), nullable=True))
    op.add_column('permission', sa.Column('model', sa.String(), nullable=True))
    op.add_column('permission', sa.Column('read', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('create', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('update', sa.Boolean(), nullable=True))
    op.add_column('permission', sa.Column('delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'delete')
    op.drop_column('permission', 'update')
    op.drop_column('permission', 'create')
    op.drop_column('permission', 'read')
    op.drop_column('permission', 'model')
    op.drop_column('permission', 'name')
    # ### end Alembic commands ###
