"""Auto-generated migration for schema sync

Revision ID: 90f02322039a
Revises: c99537b69ab1
Create Date: 2023-12-30 19:44:13.235154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f02322039a'
down_revision: Union[str, None] = 'c99537b69ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
