"""Auto-generated migration for schema sync

Revision ID: b213db8c5021
Revises: 6c65e97d240b
Create Date: 2023-12-30 19:26:24.195397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b213db8c5021'
down_revision: Union[str, None] = '6c65e97d240b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
